### ISSUE TITLE
The class RandStream has no Constant property or Static method named 'setDefaultStream'

### ISSUE THREAD

**Issue by kareth-leon** [rjgsousa/RejectOption#1]
Hi, thanks a lot for sharing your code. I tried to run it but I have this issue:
`The class RandStream has no Constant property or Static method named 'setDefaultStream'.`
I have tried different things and it doesn't work. I would like to run the SVM classifier with the reject option.
Thanks in advance.  _(I'm sorry I realized that I've wrote my comment in another project)_

**Comment by rjgsousa** [comment]
Hi.

It's still the same issue. This code was built on top of an old version of the Matlab. 

We don't support newer versions of Matlab.

Thank you for your understanding. 

Best,
Ricardo
